-- craftnet setup central
--
-- A Central Server is provisioned rather than configured: its World identity
-- and its two root secrets are generated by the External Application, and this
-- carries them across. Nothing in world invents a World Key.
--
-- Provision the World in the External Application first, which is what records
-- the digests the Gateway will check against:
--   cd external && go run ./cmd/craftnetd provision -world <id> -central <id>

local directory = fs.getDir(shell.getRunningProgram())
local bootstrap = dofile(fs.combine(directory, "bootstrap.lua"))

local packages = bootstrap.packages()
local centralPackage = dofile(fs.combine(directory, "init.lua")).withPackages(packages)
local wizard = centralPackage.wizard

local function ask(question)
  while true do
    local suffix = question.default and (" [" .. question.default .. "]") or ""
    if question.example then suffix = suffix .. " (e.g. " .. question.example .. ")" end
    write(question.prompt .. suffix .. ": ")
    local answer = question.secret and read("*") or read()
    if answer == "" and question.default then answer = question.default end
    local value, problem = question.validate(answer)
    if value ~= nil then return value end
    printError("  " .. problem)
  end
end

print("CraftNet -- Central Server provisioning")
print()
print("Read these from 'craftnetd provision'. They are shown there once.")
print()

local answers = {}
for _, question in ipairs(wizard.questions) do
  answers[question.key] = ask(question)
end

local adapters = bootstrap.adapters(packages, { root = "/craftnet" })
local central = centralPackage.new({ path = "craftnet/central", adapters = adapters })

local ok, code, detail = central:start()
if not ok then
  printError("cannot start: " .. tostring(code) .. " " .. tostring(detail))
  return
end

local provisioned, provisionCode, provisionProblem = central:provision(wizard.bundle(answers))
if not provisioned then
  printError(tostring(provisionCode) .. ": " .. tostring(provisionProblem))
  return
end

print()
print("Provisioned " .. answers.world_id .. ".")
print("Issue an ISP Enrollment Token with: token")
print("Start the Central Server with:      startup")
