-- The Central Server setup questions.
--
-- A Central Server is not configured so much as provisioned: its World identity
-- and its two root secrets are generated by the External Application, and this
-- wizard only carries them across. Nothing in world invents a World Key.

local internal = ...
local protocol = internal("protocol")

local wizard = {}

local function hexOfLength(bytes)
  return function(value)
    if type(value) ~= "string" then return nil, "a hexadecimal secret is required" end
    local cleaned = string.lower((string.gsub(value, "%s", "")))
    if #cleaned ~= bytes * 2 or not string.match(cleaned, "^[0-9a-f]+$") then
      return nil, "expected " .. (bytes * 2) .. " hexadecimal characters"
    end
    return cleaned
  end
end

wizard.SECRET_BYTES = 32

wizard.questions = {
  {
    key = "world_id",
    prompt = "World identity",
    example = "world-overworld",
    validate = function(value)
      if not protocol.validate.identifier(value) then
        return nil, "an identity is lowercase letters, digits, hyphens, and underscores"
      end
      return value
    end,
  },
  {
    key = "central_id",
    prompt = "Central Server identity",
    default = "central-main",
    validate = function(value)
      if not protocol.validate.identifier(value) then
        return nil, "an identity is lowercase letters, digits, hyphens, and underscores"
      end
      return value
    end,
  },
  {
    key = "gateway_url",
    prompt = "External Application URL",
    default = "wss://127.0.0.1:8080/gateway",
    validate = function(value)
      if type(value) ~= "string" or value == "" then return nil, "a URL is required" end
      return value
    end,
  },
  {
    key = "world_key",
    prompt = "World Key",
    secret = true,
    validate = hexOfLength(32),
  },
  {
    key = "gateway_credential",
    prompt = "Gateway Credential",
    secret = true,
    validate = hexOfLength(32),
  },
}

function wizard.validate(key, value)
  for _, question in ipairs(wizard.questions) do
    if question.key == key then return question.validate(value) end
  end
  return nil, "'" .. tostring(key) .. "' is not a setup question"
end

-- bundle is what the Central Server provisions from. It is the same shape
-- `craftnetd provision` prints, so an Operator reads the values straight off
-- that output -- which is the only time the application shows them.
function wizard.bundle(answers)
  return {
    world_id = answers.world_id,
    central_id = answers.central_id,
    gateway_url = answers.gateway_url,
    gateway_credential_ref = "gateway-credential",
    world_key = answers.world_key,
    gateway_credential = answers.gateway_credential,
  }
end

return wizard
